### ISSUE TITLE
Daily Task

### ISSUE THREAD

**Issue by Neeraj-Joshi4454** [Neeraj-Joshi4454/ReactCodebase#1]
- [x] React Routing video ( youtube )
- [x] SWOT Analysis (IMP)
- [x] Counter App (using useState Hook)
ETA : 08th may

**Comment by knikam2025** [comment]
> * [ ]  React Routing video ( youtube ) : Krishna Nikam

> * [ ]  SWOT Analysis (IMP)

> * [ ]  Counter App (using useState Hook)

>   ETA : 08th may

**Comment by gauri-saut** [comment]
> * [ ]  React Routing video ( youtube ) : completed 
> * [ ]  SWOT Analysis (IMP)
> * [ ]  Counter App (using useState Hook)
>   ETA : 08th may

**Comment by Pratibha1696** [comment]
Completed (Pratibha Pawar)
1)React Routing video ( youtube ) 
 2)SWOT Analysis (IMP)
 3)Counter App (using useState Hook)

**Comment by Biradar1422** [comment]
Priya Biradar
 1. React Routing video ( youtube ) - Done
 2. SWOT Analysis (IMP) - Done
 3. Counter App (using useState Hook) - Done

**Comment by Seema-Ughade** [comment]
Completed (seema ughade)
1)React Routing video ( youtube )
2)SWOT Analysis (IMP)
3)Counter App (using useState Hook)

**Comment by Pandey-shikha** [comment]
Completed (Shikha Pandey)
1)React Routing video ( youtube )
2)SWOT Analysis (IMP)
3)Counter App (using useState Hook)

**Comment by Pooja-Kanse-7401** [comment]
Completed (Pooja Kanse)

> * [x]  React Routing video ( youtube )
> * [x]  SWOT Analysis (IMP)
> * [x]  Counter App (using useState Hook)
>   ETA : 08th may

**Comment by RanjitPatilNode** [comment]
Completed (Ranjit )
> * [ ]  React Routing video ( youtube )
> * [ ]  SWOT Analysis (IMP)
> * [ ]  Counter App (using useState Hook)
>   ETA : 08th may

**Comment by ShrutiGalande20** [comment]
React Routing video ( youtube ) - Shruti
 SWOT Analysis (IMP)
 Counter App (using useState Hook)
ETA : 08th may

**Comment by Neeraj-Joshi4454** [comment]
completed
